# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

target 'Lumiere_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lumiere

	pod 'FirebaseCore'
	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'


end

